# Generated by Django 3.2.8 on 2021-10-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id_consultorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('piso', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'consultorio',
                'managed': False,
            },
        ),
    ]
