# Generated by Django 3.2.8 on 2021-11-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
    ]
