# Generated by Django 3.2.8 on 2021-11-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidad', '0001_initial'),
        ('perfil', '0001_initial'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinTablesmodel',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('numero_documento', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('grupo_sanguineo', models.CharField(max_length=50)),
                ('estrato', models.IntegerField()),
                ('estado_civil', models.CharField(max_length=50)),
                ('contrato', models.CharField(max_length=100)),
                ('id_agenda', models.ForeignKey(db_column='id_agenda', on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.agenda')),
                ('id_especialidad', models.ForeignKey(db_column='id_especialidad', on_delete=django.db.models.deletion.DO_NOTHING, to='especialidad.especialidad')),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.perfil')),
            ],
        ),
    ]
