# Generated by Django 3.2.8 on 2021-10-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
    ]
