# Generated by Django 3.2.8 on 2021-10-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
    ]
