# Generated by Django 3.2.8 on 2021-10-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
    ]
